blueprint:
  name: Smart Appliance Sensor Conversion Start Automation
  description: Set the start run action(s) to take to convert a dumb appliance to smart
  domain: automation
  author: EffortlessHome
  input:
    sensor:
      name: Sensor
      description:
        The sensor attached to the appliance. Typically
        a vibration, door or temperature sensor.
      selector:
        entity:
          filter:
            - domain:
                - sensor
                - binary_sensor
          multiple: false

    appliance_switch:
      name: Dedicated appliance switch
      description: Use one of the defined Appliance Switches to convert the appliance to smart.
      selector:
        entity:
          domain:
            - switch
          multiple: false

    person_input:
      name: Person
      description: The person to notify
      selector:
        entity:
          domain: person

    notification_message:
      name: Notification message
      description: "Default: Appliance Started"
      default: Appliance Started
    additional_actions:
      name: Additional Actions
      description: Add additional actions to execute (Optional)
      default: []
      selector:
        action: {}
    data_clickaction_url:
      name: URL to Navigate (Optional)
      description:
        The URL to navigate to when clicking on the notification. (default
        = /lovelace)
      default: /lovelace

trigger:
  platform: state
  entity_id: !input sensor
  from: "off"
  to: "on"

condition:
  - condition: state
    entity_id: !input appliance_switch
    state: "off"

variables:
  clickActionURL: !input data_clickaction_url

action:
  - service: effortlesshome.notify_person_service
    data:
      target: !input person_input
      title: !input notification_message
      message: !input notification_message
      data:
        clickAction: !input data_clickaction_url
        ttl: 0
        priority: high
        url: !input data_clickaction_url

  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: !input appliance_switch

  - choose: []
    default: !input additional_actions
